image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    - /release\/.*/
    - dev
    - /^(.*\/)?ci-.*$/
    - /^rel\/.*/
build_script:
  - ps: .\run.ps1 default-build
on_finish:
  - ps: "7z a testlogs.zip testlogs"
  - ps: "Push-AppveyorArtifact testlogs.zip"
install:
  - ps: Install-Product node 8
clone_depth: 1
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    ASPNETCORE_TEST_LOG_DIR: "$(APPVEYOR_BUILD_FOLDER)\\testlogs"
test: off
deploy: off
os: Visual Studio 2017
